travis:
  secure:
    BINSTAR_TOKEN: JjVSGb2wrvXk8pGL4CIeQ0QWKoQvoCuSMti5KdcA6Y6L1FpUq+N0NYkyKHfiSlWe7q7j+pH0n4bDD88VHxnRnVaDrZuQLXD4oJjqyZh2MPvrkBpnvmzehcPGyGH5FVYtpsDUX5nvUI5yNEYJPp7kg/+n29ZxuP3yVDm4qOlVEVrvMM1I4qND18tKIHeWcxmALPAtI4FdWi91A0H/C5YIddhHkdS8kjNp/ilHpoOBEbH9tmZ1HY6DI5um9jog2MuwZNpT6cBekl1ddKwJY4hDYRyNV9163KtyVcqXTtTVj3Czx5pgxxDv2k7U/qpdpJekJX9gYZrCM2FkTsT6qiIZdBLxOEgstHmvgVYc12WgVnnnbE8+UdAkMKjHs6qF+kvg07Kr6vqmxMWaZ4/dEXl8hJoVynNc5bC99IIqm4NK5zNOK6Ecubbsb2vtuKIiYWAqhT15KkcziUkbuLrmhkNTH/Rt3ipV3HGBqCS7M/eBJAgg+75NvDL197uYQSaiInfwo1LmYiXk1o90rltGIin2F2fppn/+B/2HHzU76Aqhq9rzVeSpf26fC/bev90QJcsbbVpQuMI+F+XjEpwCNZhcgCGfts6plEZqu0gmIKCzfY0/+ATLVTCklxDKkt7SMNWuEeyVjOiMj9J5IG9vNOWW5I20HXxKpQdv+IP1iTTypZY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
