travis:
  secure:
    BINSTAR_TOKEN: xGTPeayuozOuqC87U4wfEah4z3pwrHbZ8qwUEacsT7ZdIHH98hZ+YzNgnkNlilgflJeGBWCZuiPohhVxDXV8TotuSOBU9ayDnJYSVp2nkUGMDpKG15B7A1V/2EU+JKrbH8XjyqohL7Sn0dVSEQmDz/Mtm0/BxGAswdhGvxPJ4p43E0twOI1mIobwqVtXPjm72aCat5m6sItqh1Hvy6lF4APwUx0+rWzfthc+abwzAjGR0I0ul119Pscsktl98onwTD4fjs2tRXK0ZwoCnpcs+UeUdvBZquPOHZ85C+myudkQwOT0btrfcdEThnmlArfU9uE189rbxbdGPmLbWarP8Ej9lvnIWPK/Vga0hq6K8fZ+I2DUhpPGcgG20yAB7KmEWGdZv+tn8w+hBldsd70HoHTl1cip7gHccskmsKK72TsH5g74JAqecyjpEvuYNSdHD3RTqAZJfyW7oZO0hfUMw47nx+A3q59ba7spSiCHl5UFkYJdeZQrbrEReacApHqLMreQmInIpsLuw+LsSW5oc6TxrPpeACVKirtF1rja1+JFqWTITeZorRLBgJFaAZOscWycyZtzlPuehRVQQFETMhP84oLYaRaFsq6igQwrZJU5H9dquaYi9EyF36izkid1C8UFiS2Tz/e3b3QOh5vuqJpas4rbT3jeM5IW1EjH0C8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
